#!/bin/bash

## HEADER (informations about the script)
#
# Name : gd-flow (stands for Git Deployment Flow)
# Description : gd-flow is a little bash script that allows you to automate deployment using Git and the rsync command only.
# Project page : https://github.com/flawyte/gd-flow
# Version : 2
# Options :
#   *  -d   : Deployment (destination) directory - where to deploy the files - (without trailing slash)
#   * [-e]  : File containing patterns to exclude from the synchronization
#             See the "INCLUDE/EXCLUDE PATTERN RULES" part at "http://rsync.samba.org/ftp/rsync/rsync.html"
#             (default : will not exclude any file or directory)
#   *  -g   : Path to the local git repository that triggered the hook - (without trailing slash)
#   *  -s   : - Repository's subdirectory to copy content from (without trailing slash)
#             OR
#             - Path to a file containing a list of repository's subdirectories to copy content from (without trailing slashs)
#   * [-v]  : Whether you want verbose output during synchronization or not
#             (default : will only print the minimum of informations)
#
# WARNING : Don't forget to chmod +x the script so it can be triggered by Git.

read oldvalue newvalue refname # See "https://www.kernel.org/pub/software/scm/git/docs/githooks.html#post-receive" for more informations

## VARIABLES (what you have to change, either by hard coding the values or by calling the script with the appropriated options)

dep_dir=null   # -d
exc_fil=null   # -e
git_dir=null   # -g
subdirs=null   # -s
tmp_dir=null
verbose=0               # -v

## PARSE CLI Options

while getopts ":d:e:g:s:v" opt ; do
  if [[ $OPTARG == -* ]] ; then
    echo "[gd-flow] '$OPTARG' is not a valid argument for option '$opt'"
    exit 1
  fi

  case $opt in
    d)
      dep_dir=$OPTARG
      tmp_dir="$dep_dir-tmp"
    ;;
    e)
      exc_fil=$OPTARG
    ;;
    g)
      git_dir=$OPTARG
    ;;
    s)
      subdirs=$OPTARG
    ;;
    v)
      (( verbose = 1 ))
    ;;
    :)
      echo "[gd-flow] No value given for option '$OPTARG'"
      exit 1
    ;;
  esac
done

echo "[gd-flow] old_val = $oldvalue"
echo "[gd-flow] new_val = $newvalue"
echo "[gd-flow] refname = $refname"
echo "[gd-flow] dep_dir = $dep_dir"
echo "[gd-flow] exc_fil = $exc_fil"
echo "[gd-flow] git_dir = $git_dir"
echo "[gd-flow] subdirs = $subdirs"
echo "[gd-flow] verbose = $verbose"

## CHECK CLI Arguments

# dep_dir
if [ $dep_dir == null ] ; then
  echo "[gd-flow] You have to specify a deployment directory (using option '-d')"
  exit 1
fi

# exc_fil
if [[ $exc_fil != null && ! -f $exc_fil ]] ; then
  echo "[gd-flow] -e : '$exc_fil' is not a file"
  exit 1
fi

# git_dir
if [ $git_dir == null ] ; then
  echo "[gd-flow] You have to specify a git repository (using option '-g')"
  exit 1
elif [ ! -d $git_dir ] ; then
  echo "[gd-flow] -g : '$git_dir' is not a directory"
  exit 1
fi

## BUILD the command that wil be executed

cmd="rsync -a"

if [ $exc_fil != null ] ; then
  cmd="$cmd --exclude-from=$exc_fil"
fi
if [ $verbose == 1 ] ; then
  cmd="$cmd -v"
fi

## DEPLOY the files

# Create deployment dir
if [ ! -d "$dep_dir" ] ; then
  mkdir -p "$dep_dir"
  echo "[gd-flow] '$dep_dir' has been created"
fi

# Create temp dir
mkdir $tmp_dir
echo "[gd-flow] '$tmp_dir' has been created"

# Create the website files in the temp dir by doing a '--hard' reset
git --git-dir=$git_dir --work-tree=$tmp_dir reset --hard $newvalue

# Updates the content of the destination directory by using synchronization
echo "[gd-flow] Starting synchronization..."

mkdir $tmp_dir-2
echo "[gd-flow] '$tmp_dir-2' has been created"

# No subdirectories specified => add everything from the repo to the second temp dir
if [ $subdirs == null ] ; then
  $($cmd -r $tmp_dir/ $tmp_dir-2 | tee /dev/tty)
# File => add each specified repo's subdirectory's content to the second temp dir
elif [ -f $subdirs ] ; then
  cat $subdirs | while read line ; do
    $($cmd -r $tmp_dir/$line/ $tmp_dir-2 | tee /dev/tty)
  done
# String => add only this subdirectory's content to the deployment dir
else
  $($cmd -r $tmp_dir/$subdirs/ $tmp_dir-2 | tee /dev/tty)
fi

echo "[gd-flow] ...step 1 finished"
$($cmd --delete -r $tmp_dir-2/ $dep_dir | tee /dev/tty)
echo "[gd-flow] ...step 2 finished"

echo "[gd-flow] ...synchronization finished"

# Removes the temp directories and their content
rm -rf $tmp_dir
echo "[gd-flow] '$tmp_dir' has been removed"
rm -rf $tmp_dir-2
echo "[gd-flow] '$tmp_dir-2' has been removed"

# Everything went fine
echo "[gd-flow] '$refname' has been successfully deployed to '$dep_dir'"
