#!/bin/bash
# Description : gd-flow unit testing file

# ----- VARIABLES

oldvalue=123456
newvalue=456789
refname="refs/heads/master"
target="gd-flow"

# ----- FUNCTIONS

assert() {
        if [[ $1 == $2 ]] ;
        then
                echo "PASSED"
        else
                echo "FAILED"
        fi
}

# ----- CHECK

if [[ $# == 1 && -f "$1" ]] ;
then
        target=$1
fi

# ----- UNITS TESTING

# No deploy / git directory & no exclude file
result_str=$( echo $oldvalue $newvalue $refname | bash $target )
result_code=$?
assert_str=$( assert $result_code 1 )
echo "$assert_str ($result_code) $result_str"

# No git directory & no exclude file
result_str=$( echo $oldvalue $newvalue $refname | bash $target -d "units-testing/deploy-directory" )
result_code=$?
assert_str=$( assert $result_code 1 )
echo "$assert_str ($result_code) $result_str"

# Wrong git directory & no exclude file
result_str=$( echo $oldvalue $newvalue $refname | bash $target -d "units-testing/deploy-directory" -g "units-testing/git-directory" )
result_code=$?
assert_str=$( assert $result_code 1 )
echo "$assert_str ($result_code) $result_str"

# Wrong exclude file
result_str=$( echo $oldvalue $newvalue $refname | bash $target -d "units-testing/deploy-directory" -g ".git" -e fake )
result_code=$?
assert_str=$( assert $result_code 1 )
echo "$assert_str ($result_code) $result_str"
